version: '3'

services:
  mysql-01: 
    image: mysql:8.0
    container_name: mysql-01
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: datalogic
      MYSQL_USER: dataloc
      MYSQL_PASSWORD: datalogic
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-01:/var/lib/mysql
  mongodb:
    image: mongo
    container_name: mongodb-01
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpw
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
